export const business = {
  name: 'Black Forest Bakery & Sweets',
  shortName: 'Black Forest',
  tagline: 'Freshly baked. Beautifully crafted.',
  description: 'A premium bakery and sweets storefront demo designed for local celebrations and everyday treats.',
  locationLabel: 'Ghora Sahan, Bihar, India',
  phone: '' as string,
  whatsapp: '' as string,
  email: '' as string,
  address: 'Ghora Sahan, Bihar, India',
  city: 'Ghora Sahan',
  state: 'Bihar',
  postalCode: '' as string,
  mapsUrl: '' as string,
  latitude: null as number | null,
  longitude: null as number | null,
  timezone: 'Asia/Kolkata',
  currency: 'INR',
  deliveryEnabled: true,
  pickupEnabled: true,
  deliveryCharge: 0,
  minimumOrder: 0,
  demoMode: true,
  announcement: 'Custom Cakes • Fresh Bakery • Sweet Moments',
  hero: {
    eyebrow: 'BAKERY & SWEETS',
    title: 'Freshly baked.\nBeautifully crafted.',
    text: 'Delicious cakes, sweets and bakery favourites made for birthdays, celebrations and everyday moments.',
  },
  seo: {
    title: 'Black Forest Bakery & Sweets | Ghora Sahan',
    description: 'Explore cakes, sweets and bakery favourites from a reusable premium local bakery website demo.',
  },
  social: { instagram: '' as string, facebook: '' as string, youtube: '' as string },
  hours: [
    ['Monday', '10:00 AM – 10:00 PM'],
    ['Tuesday', '10:00 AM – 10:00 PM'],
    ['Wednesday', '10:00 AM – 10:00 PM'],
    ['Thursday', '10:00 AM – 10:00 PM'],
    ['Friday', '10:00 AM – 10:00 PM'],
    ['Saturday', '10:00 AM – 10:00 PM'],
    ['Sunday', '10:00 AM – 10:00 PM'],
  ] as const,
} as const

export const isConfigured = (value: string) => value.trim().length > 0
