import { useEffect, useState } from 'react'
import { Link, Navigate, Route, Routes } from 'react-router-dom'
import { business } from '../../config/business'
import { categories, products } from '../../data/demo'
import { supabase } from '../../lib/supabase'
import ProductAdmin, { ProductList } from './ProductAdmin'

function Gate(){const [state,setState]=useState<'loading'|'signed-out'|'allowed'>('loading');useEffect(()=>{let alive=true;const client=supabase;if(!client){setState('signed-out');return}const check=async()=>{const {data}=await client.auth.getUser();if(!data.user){if(alive)setState('signed-out');return}const {data:profile}=await client.from('profiles').select('is_active,role').eq('id',data.user.id).maybeSingle();if(alive)setState(profile?.is_active&&['owner','admin','manager','staff'].includes(profile.role)?'allowed':'signed-out')};void check();return()=>{alive=false}},[]);if(state==='loading')return <div className="page"><div className="container narrow simple"><div className="eyebrow">ADMIN</div><h1>Checking access…</h1><p>Verifying your authenticated staff session.</p></div></div>;if(state!=='allowed')return <Navigate to="/admin/login" replace/>;return <Dashboard/>}
function Dashboard(){return <div className="page"><div className="container"><div className="page-title"><div className="eyebrow">ADMIN</div><h1>Good morning.</h1><p>Manage the reusable bakery storefront. Customer metrics remain blank until real data is connected.</p></div><div className="admin-grid"><AdminCard to="/admin/products" title="Products" text={`${products.length} demo catalogue items · live CRUD ready`}/><AdminCard to="/admin/categories" title="Categories" text={`${categories.length} editable categories`}/><AdminCard to="/admin/orders" title="Orders" text="Customer orders stay private in Supabase"/><AdminCard to="/admin/custom-cakes" title="Custom Cakes" text="Review incoming cake briefs"/><AdminCard to="/admin/offers" title="Offers" text="Configure verified promotions"/><AdminCard to="/admin/gallery" title="Gallery" text="Manage inspiration imagery"/><AdminCard to="/admin/settings" title="Settings" text="Business, hours, SEO and social"/><AdminCard to="/admin/team" title="Team" text="Roles and access"/></div></div></div>}
function AdminCard({to,title,text}:{to:string;title:string;text:string}){return <Link className="admin-card" to={to}><h2>{title}</h2><p>{text}</p><span>Open →</span></Link>}
function Listing({title,items}:{title:string;items:string[]}){return <div className="page"><div className="container"><div className="page-title"><div className="eyebrow">ADMIN / {title.toUpperCase()}</div><h1>{title}</h1></div><div className="admin-list">{items.map(x=><div key={x}><strong>{x}</strong><span>Demo / awaiting Supabase persistence</span></div>)}</div></div></div>}
export default function Admin(){return <Routes><Route index element={<Gate/>}/><Route path="products" element={<ProductList/>}/><Route path="products/new" element={<ProductAdmin/>}/><Route path="products/:id/edit" element={<ProductEditor/>}/><Route path="categories" element={<Listing title="Categories" items={categories.map(c=>c.name)}/>}/><Route path="orders" element={<Listing title="Orders" items={['No live orders yet']}/>}/><Route path="custom-cakes" element={<Listing title="Custom Cake Requests" items={['No live requests yet']}/>}/><Route path="offers" element={<Listing title="Offers" items={['No verified offers configured']}/>}/><Route path="gallery" element={<Listing title="Gallery" items={['Gallery storage ready for Supabase setup']}/>}/><Route path="settings" element={<Listing title="Settings" items={[business.name,'Contact & WhatsApp','Location & Maps','Opening hours','Social links','SEO']}/>}/><Route path="team" element={<Listing title="Team" items={['Owner / Admin roles are managed through Supabase Auth']}/>}/><Route path="*" element={<Navigate to="/admin" replace/>}/></Routes>}
function ProductEditor(){return <ProductEditorInner/>}
function ProductEditorInner(){const path=window.location.pathname;const id=path.split('/').filter(Boolean).pop();return <ProductAdmin id={id}/>}
