import { Link, Navigate, Route, Routes } from 'react-router-dom'
import { business } from '../../config/business'
import { categories, products } from '../../data/demo'

function Gate(){const configured=Boolean(import.meta.env.VITE_SUPABASE_URL&&import.meta.env.VITE_SUPABASE_ANON_KEY); if(!configured)return <div className="page"><div className="container narrow simple"><div className="eyebrow">ADMIN SETUP</div><h1>Connect Supabase to unlock the CMS.</h1><p>The demo storefront works without credentials. Configure Supabase and Auth before exposing admin functionality.</p><Link className="btn primary" to="/">Back Home</Link></div></div>; return <Dashboard/>}
function Dashboard(){return <div className="page"><div className="container"><div className="page-title"><div className="eyebrow">ADMIN</div><h1>Good morning.</h1><p>Manage the reusable bakery storefront. Customer metrics remain blank until real data is connected.</p></div><div className="admin-grid"><AdminCard to="/admin/products" title="Products" text={`${products.length} demo catalogue items`}/><AdminCard to="/admin/categories" title="Categories" text={`${categories.length} editable categories`}/><AdminCard to="/admin/orders" title="Orders" text="Customer orders stay private in Supabase"/><AdminCard to="/admin/custom-cakes" title="Custom Cakes" text="Review incoming cake briefs"/><AdminCard to="/admin/offers" title="Offers" text="Configure verified promotions"/><AdminCard to="/admin/gallery" title="Gallery" text="Manage inspiration imagery"/><AdminCard to="/admin/settings" title="Settings" text="Business, hours, SEO and social"/><AdminCard to="/admin/team" title="Team" text="Roles and access"/></div></div></div>}
function AdminCard({to,title,text}:{to:string;title:string;text:string}){return <Link className="admin-card" to={to}><h2>{title}</h2><p>{text}</p><span>Open →</span></Link>}
function Listing({title,items}:{title:string;items:string[]}){return <div className="page"><div className="container"><div className="page-title"><div className="eyebrow">ADMIN / {title.toUpperCase()}</div><h1>{title}</h1></div><div className="admin-list">{items.map(x=><div key={x}><strong>{x}</strong><span>Demo / awaiting Supabase persistence</span></div>)}</div></div></div>}
export default function Admin(){return <Routes><Route index element={<Gate/>}/><Route path="products" element={<Listing title="Products" items={products.map(p=>p.name)}/>}/><Route path="categories" element={<Listing title="Categories" items={categories.map(c=>c.name)}/>}/><Route path="orders" element={<Listing title="Orders" items={['No live orders yet']}/>}/><Route path="custom-cakes" element={<Listing title="Custom Cake Requests" items={['No live requests yet']}/>}/><Route path="offers" element={<Listing title="Offers" items={['No verified offers configured']}/>}/><Route path="gallery" element={<Listing title="Gallery" items={['Gallery storage ready for Supabase setup']}/>}/><Route path="settings" element={<Listing title="Settings" items={[business.name,'Contact & WhatsApp','Location & Maps','Opening hours','Ordering','Social links','SEO']}/>}/><Route path="team" element={<Listing title="Team" items={['Owner / Admin roles are managed through Supabase Auth']}/>}/><Route path="*" element={<Navigate to="/admin" replace/>}/></Routes>}
