import { useEffect, useState } from 'react'
import { Link, Navigate, Route, Routes } from 'react-router-dom'
import { categories, products } from '../../data/demo'
import { supabase } from '../../lib/supabase'
import ProductAdmin, { ProductList } from './ProductAdmin'
import { OrderDetail, OrdersList } from './OrdersAdmin'
import { CategoriesAdmin, CustomCakesAdmin, GalleryAdmin, OffersAdmin, ReviewsAdmin, SettingsAdmin } from './AdminManagement'
function Gate(){const[state,setState]=useState<'loading'|'signed-out'|'allowed'>('loading');useEffect(()=>{let alive=true;const client=supabase;if(!client){setState('signed-out');return}const check=async()=>{const{data}=await client.auth.getUser();if(!data.user){if(alive)setState('signed-out');return}const{data:profile}=await client.from('profiles').select('is_active,role').eq('id',data.user.id).maybeSingle();if(alive)setState(profile?.is_active&&['owner','admin','manager','staff'].includes(profile.role)?'allowed':'signed-out')};void check();return()=>{alive=false}},[]);if(state==='loading')return <div className="page"><div className="container narrow simple"><div className="eyebrow">ADMIN</div><h1>Checking access…</h1><p>Verifying your authenticated staff session.</p></div></div>;if(state!=='allowed')return <Navigate to="/admin/login" replace/>;return <Dashboard/>}
function Dashboard(){return <div className="page"><div className="container"><div className="page-title"><div className="eyebrow">ADMIN</div><h1>Good morning.</h1><p>Manage catalogue, orders, cake requests, promotions, gallery, reviews and business settings.</p></div><div className="admin-grid"><AdminCard to="/admin/products" title="Products" text={`${products.length} demo catalogue items · live CRUD`}/><AdminCard to="/admin/categories" title="Categories" text={`${categories.length} demo categories · live CRUD`}/><AdminCard to="/admin/orders" title="Orders" text="Private live orders with status management"/><AdminCard to="/admin/custom-cakes" title="Custom Cakes" text="Review and update incoming cake briefs"/><AdminCard to="/admin/offers" title="Offers" text="Create and enable verified promotions"/><AdminCard to="/admin/gallery" title="Gallery" text="Publish, hide and delete gallery records"/><AdminCard to="/admin/reviews" title="Reviews" text="Moderate verified and demo reviews"/><AdminCard to="/admin/settings" title="Settings" text="Business contact, delivery, payments and SEO"/><AdminCard to="/admin/team" title="Team" text="Roles and access"/></div></div></div>}
function AdminCard({to,title,text}:{to:string;title:string;text:string}){return <Link className="admin-card" to={to}><h2>{title}</h2><p>{text}</p><span>Open →</span></Link>}
function Team(){return <div className="page"><div className="container"><div className="page-title"><div className="eyebrow">ADMIN / TEAM</div><h1>Team</h1><p>Team membership and roles are controlled through Supabase Auth and the profiles table. Passwords are never stored here.</p></div><div className="info-note">Create/authenticate users in Supabase, then add their profile row with role owner, admin, manager or staff and an active flag.</div></div></div>}
export default function Admin(){return <Routes><Route index element={<Gate/>}/><Route path="products" element={<ProductList/>}/><Route path="products/new" element={<ProductAdmin/>}/><Route path="products/:id/edit" element={<ProductEditor/>}/><Route path="categories" element={<CategoriesAdmin/>}/><Route path="orders" element={<OrdersList/>}/><Route path="orders/:id" element={<OrderRoute/>}/><Route path="custom-cakes" element={<CustomCakesAdmin/>}/><Route path="offers" element={<OffersAdmin/>}/><Route path="gallery" element={<GalleryAdmin/>}/><Route path="reviews" element={<ReviewsAdmin/>}/><Route path="settings" element={<SettingsAdmin/>}/><Route path="team" element={<Team/>}/><Route path="*" element={<Navigate to="/admin" replace/>}/></Routes>}
function ProductEditor(){return <ProductAdmin id={window.location.pathname.split('/').filter(Boolean).pop()}/>}
function OrderRoute(){return <OrderDetail id={window.location.pathname.split('/').filter(Boolean).pop()??''}/>}
