import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { Save } from 'lucide-react'
import { supabase } from '../../lib/supabase'

type Customer = { id:string; full_name:string|null; phone:string|null; cashback_balance:number; created_at:string }
type DiscountRequest = { id:string; customer_id:string; order_id:string|null; request_note:string; status:string; requested_at:string; customer?:Customer|null }

export default function CustomersAdmin(){
 const [customers,setCustomers]=useState<Customer[]>([]); const [requests,setRequests]=useState<DiscountRequest[]>([]); const [loading,setLoading]=useState(true); const [message,setMessage]=useState(''); const [saving,setSaving]=useState<string|null>(null)
 const load=async()=>{if(!supabase){setLoading(false);return};setLoading(true);const [c,r]=await Promise.all([supabase.from('customer_profiles').select('id,full_name,phone,cashback_balance,created_at').order('created_at',{ascending:false}),supabase.from('discount_requests').select('id,customer_id,order_id,request_note,status,requested_at').eq('status','pending').order('requested_at',{ascending:false})]);if(c.error)setMessage(c.error.message);else setCustomers((c.data??[]) as Customer[]);if(r.error)setMessage(r.error.message);else setRequests((r.data??[]) as DiscountRequest[]);setLoading(false)}
 useEffect(()=>{void load()},[])
 const saveCashback=async(c:Customer)=>{if(!supabase)return;setSaving(c.id);setMessage('');const {error}=await supabase.from('customer_profiles').update({cashback_balance:Math.max(0,Number(c.cashback_balance)||0)}).eq('id',c.id);setSaving(null);setMessage(error?.message||'Cashback balance saved.');if(!error)await load()}
 const review=async(r:DiscountRequest,status:'approved'|'declined')=>{if(!supabase)return;setSaving(r.id);setMessage('');const {error}=await supabase.from('discount_requests').update({status,reviewed_at:new Date().toISOString()}).eq('id',r.id);setSaving(null);setMessage(error?.message||`Discount request ${status}.`);if(!error)await load()}
 return <div className="page"><div className="container"><div className="page-title"><div className="eyebrow">ADMIN / CUSTOMERS</div><h1>Customers & rewards</h1><p>Persistent customer profiles, cashback balances and discount requests.</p></div>{message&&<div className="info-note" role="alert">{message}</div>}{loading?<p>Loading customers…</p>:<><section className="admin-panel"><h2>Customer accounts</h2>{customers.length?<div className="admin-list">{customers.map(c=><div key={c.id}><div><strong>{c.full_name||'Unnamed customer'}</strong><span>{c.phone||'Phone not provided'} · Joined {new Date(c.created_at).toLocaleDateString('en-IN')}</span></div><label className="inline-field">Cashback <input type="number" min="0" step="1" value={c.cashback_balance} onChange={e=>setCustomers(list=>list.map(x=>x.id===c.id?{...x,cashback_balance:Number(e.target.value)}:x))}/><button className="btn secondary" disabled={saving===c.id} onClick={()=>void saveCashback(c)}><Save size={14}/>{saving===c.id?'Saving':'Save'}</button></label></div>)}</div>:<div className="empty-state"><h2>No customer accounts yet.</h2><p>Customers appear here after creating an account.</p></div>}</section><section className="admin-panel"><h2>Discount requests</h2>{requests.length?<div className="admin-list">{requests.map(r=><div key={r.id}><div><strong>{r.request_note}</strong><span>Order: {r.order_id||'General request'} · {new Date(r.requested_at).toLocaleString('en-IN')}</span></div><div className="order-actions"><button className="btn primary" disabled={saving===r.id} onClick={()=>void review(r,'approved')}>Approve</button><button className="text-btn" disabled={saving===r.id} onClick={()=>void review(r,'declined')}>Reject</button></div></div>)}</div>:<p>No pending discount requests.</p>}</section><Link to="/admin" className="text-btn">← Back to dashboard</Link></>}</div></div>
}
