import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowLeft, Eye, Save } from 'lucide-react'
import { supabase } from '../../lib/supabase'

type Order = { id:string; order_number:string; customer_name:string; customer_phone:string; customer_email:string|null; order_type:'pickup'|'delivery'; delivery_address:string|null; landmark:string|null; city:string|null; postal_code:string|null; scheduled_date:string|null; scheduled_time:string|null; subtotal:number; discount_amount:number; delivery_fee:number; total_amount:number; status:string; payment_status:string; customer_note:string|null; created_at:string }
type Item = { id:string; product_name_snapshot:string; variant_name_snapshot:string|null; quantity:number; unit_price:number; line_total:number }
const statuses=['awaiting_confirmation','confirmed','preparing','ready','out_for_delivery','completed','cancelled']
const label=(s:string)=>s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())
const money=(n:number)=>`₹${Number(n).toLocaleString('en-IN')}`

export function OrdersList(){
 const [orders,setOrders]=useState<Order[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
 const load=async()=>{ if(!supabase){setLoading(false);return}; const {data,error}=await supabase.from('orders').select('id,order_number,customer_name,customer_phone,customer_email,order_type,delivery_address,landmark,city,postal_code,scheduled_date,scheduled_time,subtotal,discount_amount,delivery_fee,total_amount,status,payment_status,customer_note,created_at').order('created_at',{ascending:false}); if(error)setError(error.message); else setOrders((data??[]) as Order[]); setLoading(false) }
 useEffect(()=>{void load()},[])
 return <div className="page"><div className="container"><div className="page-title"><div className="eyebrow">ADMIN / ORDERS</div><h1>Orders</h1><p>Customer orders are private and visible only to authenticated staff.</p></div>{error&&<div className="info-note" role="alert">{error}</div>}{loading?<p>Loading orders…</p>:orders.length===0?<div className="empty-state"><h2>No orders yet</h2><p>New checkout requests will appear here after Supabase is configured.</p></div>:<div className="admin-list">{orders.map(o=><div key={o.id}><div><strong>{o.order_number}</strong><span>{o.customer_name} · {label(o.order_type)} · {money(o.total_amount)}</span><span>{label(o.status)} · Payment: {label(o.payment_status)}</span></div><Link className="text-btn" to={`/admin/orders/${o.id}`}><Eye size={15}/> View</Link></div>)}</div>}</div></div>
}

export function OrderDetail({id}:{id:string}){
 const [order,setOrder]=useState<Order|null>(null); const [items,setItems]=useState<Item[]>([]); const [status,setStatus]=useState(''); const [saving,setSaving]=useState(false); const [message,setMessage]=useState('')
 useEffect(()=>{let alive=true;const load=async()=>{if(!supabase)return;const [o,i]=await Promise.all([supabase.from('orders').select('id,order_number,customer_name,customer_phone,customer_email,order_type,delivery_address,landmark,city,postal_code,scheduled_date,scheduled_time,subtotal,discount_amount,delivery_fee,total_amount,status,payment_status,customer_note,created_at').eq('id',id).maybeSingle(),supabase.from('order_items').select('id,product_name_snapshot,variant_name_snapshot,quantity,unit_price,line_total').eq('order_id',id)]);if(!alive)return;if(o.error) setMessage(o.error.message); else {const row=o.data as Order|null;setOrder(row);setStatus(row?.status??'')};if(i.error)setMessage(i.error.message);else setItems((i.data??[]) as Item[])};void load();return()=>{alive=false}},[id])
 const save=async()=>{if(!supabase||!order)return;setSaving(true);setMessage('');const {error}=await supabase.from('orders').update({status}).eq('id',order.id);setSaving(false);if(error)setMessage(error.message);else setOrder({...order,status})}
 if(!order)return <div className="page"><div className="container narrow"><Link to="/admin/orders" className="text-btn"><ArrowLeft size={16}/> Orders</Link><h1>Order</h1><p>{message||'Loading order…'}</p></div></div>
 return <div className="page"><div className="container narrow"><div className="page-title"><Link to="/admin/orders" className="text-btn"><ArrowLeft size={16}/> Orders</Link><div className="eyebrow">ORDER {order.order_number}</div><h1>{order.customer_name}</h1><p>{order.customer_phone}{order.customer_email?` · ${order.customer_email}`:''}</p></div><section className="admin-panel"><h2>Items</h2>{items.map(i=><div className="order-line" key={i.id}><span>{i.product_name_snapshot}{i.variant_name_snapshot?` — ${i.variant_name_snapshot}`:''} × {i.quantity}</span><strong>{money(i.line_total)}</strong></div>)}<div className="order-totals"><span>Subtotal <b>{money(order.subtotal)}</b></span><span>Discount <b>-{money(order.discount_amount)}</b></span><span>Delivery <b>{money(order.delivery_fee)}</b></span><span>Total <b>{money(order.total_amount)}</b></span></div></section><section className="admin-panel"><h2>Fulfilment</h2><p><strong>{label(order.order_type)}</strong>{order.scheduled_date?` · ${order.scheduled_date}`:''}{order.scheduled_time?` · ${order.scheduled_time}`:''}</p>{order.order_type==='delivery'&&<p>{[order.delivery_address,order.landmark,order.city,order.postal_code].filter(Boolean).join(', ')}</p>}{order.customer_note&&<p>Note: {order.customer_note}</p>}</section><section className="admin-panel"><h2>Status</h2><div className="form-grid"><label>Order status<select value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label><label>Payment status<input value={label(order.payment_status)} readOnly/></label></div>{message&&<div className="info-note" role="alert">{message}</div>}<button className="btn primary" disabled={saving||status===order.status} onClick={()=>void save()}>{saving?'Saving…':<><Save size={16}/> Save status</>}</button></section></div></div>
}
